application: parsers
version: test
runtime: python27
api_version: 1
threadsafe: true

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (settingslocal\.py)|
 (node_modules)|
 )$

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /_ah/queue/async.*
  script: furious_router.app
  login: admin

- url: '/_check'
  script: demo.app

- url: '/article'
  script: demo.app

- url: .*
  script: main.app
  login: required
