application: parsers
version: test
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:

- url: /_ah/queue/async.*
  script: furious_router.app
    login: admin

- url: .*
  script: main.app
